@types缺失错误
error TS2688: Cannot find type definition file for 'mime'.
  The file is in the program because:
    Entry point for implicit type library 'mime'

error TS2688: Cannot find type definition file for 'parse-json'.
  The file is in the program because:
    Entry point for implicit type library 'parse-json'

error TS2688: Cannot find type definition file for 'prettier'.
  The file is in the program because:
    Entry point for implicit type library 'prettier'